require("user.plugins")
require("user.alpha")
require("user.bufferline")
-- require("user.dap")
require("user.keymappings")
require("user.lsp")
require("user.lualine")
require("user.notify")
require("user.neo-tree")
require("user.settings")
require("user.telescope")
require("user.terminal")
require("user.treesitter")
require("user.whichkey")

